name: Deploy to GitHub Pages
env:
  PUBLISH_DIR: bin/Release/net7.0/publish/wwwroot
# Run workflow on every push to the master branch
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        lfs: true
        token: ${{ secrets.PAT }}

    - name: Publish app
      run: dotnet publish -c Release

    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /jd-quiz-blazor/

    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.5.1
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
